title: <p align="center"> Shraddha Singh </p>
logo: /assets/img/logo2.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/">LinkedIn</a> |
  <a href="https://github.com/ShraddhaS1ngh">GitHub</a>
  
  <br>
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  <br>
  

  </p>



theme: jekyll-theme-minimal
